apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webcolor-blue-green
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/iadocicco-ale/web-color-deploy.git
    targetRevision: HEAD
    path: blue-green
  destination:
    server: https://kubernetes.default.svc
    namespace: webcolor
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true